# Lab 1: Fundamentals of Python Programming with NumPy

Welcome to the first lab session for the Image Processing course. This lab will focus on getting comfortable with NumPy and basic Python programming practices using Jupyter Notebook in Visual Studio Code.

## 1. Introduction and Setup:
### 1.1 Software Requirements
To complete this lab, you will need the following software installed on your system:
- **Python:** Version 3.9 or newer is recommended.
- **Visual Studio Code (VS Code):** A powerful and free code editor.
- **Jupyter Extension for VS Code:** This extension allows you to run Jupyter Notebooks directly within VS Code. Install it from the VS Code Extensions Marketplace.
- **NumPy Library:** The fundamental package for numerical computation in Python.

### 1.2 Setting Up Your Environment
It is highly recommended to use [a virtual environment](https://docs.python.org/3/library/venv.html) for your Python projects. This helps manage dependencies and avoids conflicts between different projects.
1. Open VS Code's Integrated Terminal
2. Navigate to your desired lab directory if needed.
3. Create a virtual environment:
```bash
        python -m venv .lab1
```
4. Activate the virtual environment:
```bash
        .lab1\Scripts\activate
```
5. Install the necessary Python packages
```bash
        pip install ipykernel numpy
```

## 2. Instructions:
- Follow the instructions in each section.
- Implement your solutions in the provided function blocks.
- Do not rename the functions, this will be used later for automated testing.

## 3. Submission Guidelines:
- **File Format:** Ensure your submission is a Jupyter Notebook file.
- **File Naming Convention:** Rename your lab file in the following format:
    - Lab1_StudentName_StudentLastName_StudentID.ipynb
- **Submission:** Please submit the zip file of Jupyter Notebook file to Moodle after you have completed.
    - Lab1_StudentName_StudentLastName_StudentID.zip

---

## 1. NumPy in Jupyter with Visual Code

### Assignment 1.1: Import NumPy

**Explanation**: NumPy is a powerful library for numerical operations. Use `import numpy as np` to access its features.

In [216]:
# TODO: Import numpy as np
import numpy as np

### Assignment 1.2: Create a 2D array of size 3x3 with all zeros

**Explanation**: You can use `np.zeros((3,3))` to create a 3x3 array filled with zeros.

In [217]:
# TODO: Create a 2D array of shape (3,3) filled with zeros
def create_zero_array() -> np.ndarray:
    return np.zeros((3, 3))

**Correctness Verification:**

In [218]:
print(create_zero_array())

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Assignment 1.3: Create a 2D array of size 3x3 with random integers from 1 to 10

**Explanation**: Use `np.random.randint(low, high, size=(rows, cols))` for random integers.

In [219]:
# TODO: Create a 2D array of shape (3,3) with random values
def create_random_array() -> np.ndarray:
    return np.random.randint(1, 11, size=(3, 3))

**Correctness Verification:**

In [220]:
print(create_random_array())

[[1 1 2]
 [5 8 8]
 [3 4 6]]


### Assignment 1.4: Create an identity matrix of size 4x4

**Explanation**: `np.eye(n)` creates an n x n identity matrix.

Identity matrices are square matrices with ones on the main diagonal (from top-left to bottom-right) and zeros elsewhere. For example, a 4×4 identity matrix looks like:

$$
I_4 = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
\end{bmatrix}
$$

In [221]:
# TODO: Create a 4x4 identity matrix
def create_identity_matrix() -> np.ndarray:
    return np.eye(4)

**Correctness Verification:**

In [222]:
print(create_identity_matrix())

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Assignment 1.5: Multiply a 2x3 matrix with a 3x2 matrix

**Explanation**: Use `np.dot(arr1, arr2)` or the `@` operator to perform matrix multiplication.


Matrix multiplication (also called the dot product) is not element-wise. Instead, each entry in the resulting matrix is computed as the dot product of a row from the first matrix and a column from the second.

#### Example:

Let’s multiply a \( 2 $\times$ 3 \) matrix with a \( 3 $\times$ 2 \) matrix:

$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}, \quad
B = \begin{bmatrix}
7 & 8 \\
9 & 10 \\
11 & 12 \\
\end{bmatrix}
$

To multiply \( A $\cdot$ B \), the number of columns in \( A \) must equal the number of rows in \( B \). The resulting matrix will be of shape \( 2 $\times$ 2 \):

$
AB = \begin{bmatrix}
(1*7 + 2*9 + 3*11) & (1*8 + 2*10 + 3*12) \\
(4*7 + 5*9 + 6*11) & (4*8 + 5*10 + 6*12) \\
\end{bmatrix}
= \begin{bmatrix}
58 & 64 \\
139 & 154 \\
\end{bmatrix}
$

#### Rules of Matrix Multiplication:
- If \( A \) is of shape \( m $\times$ n \), and \( B \) is \( n $\times$ p \), then \( A $\cdot$ B \) is defined and results in a matrix of shape \( m $\times$ p \).
- Matrix multiplication is **associative**: \( (AB)C = A(BC) \)
- It is **not commutative**: \( AB $\neq$ BA \) in general.

#### Useful NumPy Functions:
- `np.dot(A, B)` – Standard matrix multiplication.
- `A @ B` – Equivalent and often preferred for readability.
- `np.matmul(A, B)` – Also performs matrix multiplication, especially for multidimensional arrays.
- `np.transpose(A)` or `A.T` – Transposes a matrix, useful in aligning shapes for multiplication.


In [223]:
# TODO: Multiply two matrices and return the result
def multiply_matrices(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    return np.dot(A, B)

**Correctness Verification:**

In [224]:
matrix_A = np.array([[1, 2, 3], [4, 5, 6]])
matrix_B = np.array([[7, 8], [9, 10], [11, 12]])

print("Array A:")
print(matrix_A)
print("Array B:")
print(matrix_B)
result = multiply_matrices(matrix_A, matrix_B)
print("Result of A @ B:")
print(result)

Array A:
[[1 2 3]
 [4 5 6]]
Array B:
[[ 7  8]
 [ 9 10]
 [11 12]]
Result of A @ B:
[[ 58  64]
 [139 154]]


---

## 2. 2D Arrays

### Assignment 2.1: Create a 2D array from a list of lists

**Explanation**: Use `np.array(list_of_lists)` to convert a list of lists into a NumPy array.

In [225]:
# TODO: Convert a list of lists to a NumPy 2D array
def list_to_array(lst: list) -> np.ndarray:
    return np.array(lst)

**Correctness Verification:**

In [226]:
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_from_list = list_to_array(list_of_lists)
print("Array from list of lists:")
print(array_from_list)
print(type(array_from_list))

Array from list of lists:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


### Assignment 2.2: Return the shape of a 2D array

**Explanation**: The shape of an array can be obtained using `.shape`.

In [227]:
# TODO: Return the shape of the array
def array_shape(arr: np.ndarray) -> tuple:
    return arr.shape

**Correctness Verification:**

In [228]:
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of the array:")
print(array_shape(np_array))

Shape of the array:
(2, 3)


### Assignment 2.3: Access the first row of a 2D array

**Explanation**: Access rows using indexing like `arr[0]`.

In [229]:
# TODO: Return the first row
def first_row(arr: np.ndarray) -> np.ndarray:
    return arr[0]

**Correctness Verification:**

In [230]:
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("First row of the array:")
print(first_row(np_array))

First row of the array:
[1 2 3]


### Assignment 2.4: Access the last column of a 2D array

**Explanation**: Use slicing like `arr[:, -1]` to get the last column.

In [231]:
# TODO: Return the last column
def last_column(arr: np.ndarray) -> np.ndarray:
    return arr[:, -1]

**Correctness Verification:**

In [232]:
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("Last column of the array:")
print(last_column(np_array))

Last column of the array:
[3 6]


### Assignment 2.5: Add two 2D arrays element-wise

**Explanation**: You can add two arrays element-wise using the `+` operator.

In [233]:
# TODO: Add arrays element-wise
def add_arrays(arr1: np.ndarray, arr2: np.ndarray) -> np.ndarray:
    return arr1 + arr2

**Correctness Verification:**

In [234]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
print("Array A:")
print(A)
print("Array B:")
print(B)
result = add_arrays(A, B)
print("Result of A + B:")
print(result)

Array A:
[[1 2 3]
 [4 5 6]]
Array B:
[[ 7  8  9]
 [10 11 12]]
Result of A + B:
[[ 8 10 12]
 [14 16 18]]


---

## 3. If-Else in 2D Arrays

### Assignment 3.1: Return True if any element > 10

**Explanation**: Use conditionals and `np.any(arr > 10)` to check this.

In [235]:
# TODO: Check if any elements in the array are greater than ten
def check_greater_than_ten(arr: np.ndarray) -> bool:
    return np.any(arr > 10).item()

**Correctness Verification:**

In [236]:
np_array_A = np.array([[1, 2, 3], [4, 5, 6]])
print(check_greater_than_ten(np_array_A))
np_array_B = np.array([[11, 2, 3], [4, 5, 6]]) # Example with an element greater than 10
print(check_greater_than_ten(np_array_B))

False
True


### Assignment 3.2: Replace elements < 0 with 0

**Explanation**: Use boolean indexing: `arr[arr < 0] = 0`.

In [237]:
# TODO: Replace negative values in the array with zero
def replace_negatives(arr: np.ndarray) -> np.ndarray:
     arr[arr < 0] = 0
     return arr

**Correctness Verification:**

In [238]:
np_array = np.array([[1, -2, 3], 
                     [-4, 5, -6]])
print("Original array:")
print(np_array)
print("Array after replacing negatives with zero:")
print(replace_negatives(np_array))

Original array:
[[ 1 -2  3]
 [-4  5 -6]]
Array after replacing negatives with zero:
[[1 0 3]
 [0 5 0]]


### Assignment 3.3: Count elements > 5

**Explanation**: Use `np.sum(arr > 5)` to count the number of elements greater than 5.

In [239]:
# TODO: Count how many elements in the array are greater than five
def count_greater_than_five(arr: np.ndarray) -> int:
    return np.sum(arr > 5).item()

**Correctness Verification:**

In [240]:
np_array = np.array([[4, 5, 6], 
                     [7, 8, 9]])
print("Number of elements greater than five:")
print(count_greater_than_five(np_array))

Number of elements greater than five:
4


### Assignment 3.4: Mark even numbers with 1, others with 0

**Explanation**: Use `np.where(condition, value_if_true, value_if_false)` and modulo operation and boolean indexing: `arr % 2 == 0`.

In [241]:
# TODO: Mark even numbers in the array with 1, and odd numbers with 0
def mark_even(arr: np.ndarray) -> np.ndarray:
    marked_array = np.zeros(arr.shape, dtype=int)
    marked_array[arr % 2 == 0] = 1
    return marked_array

**Correctness Verification:**

In [242]:
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("Original array:")
print(np_array)
print("Array with even numbers marked with 1 and odd numbers with 0:")
print(mark_even(np_array))

Original array:
[[1 2 3]
 [4 5 6]]
Array with even numbers marked with 1 and odd numbers with 0:
[[0 1 0]
 [1 0 1]]


### Assignment 3.5: Conditional sum of elements > 5

**Explanation**: Use `np.sum(arr[arr > 5])` or `arr[arr > 5].sum()`.

In [243]:
# TODO: Sum all elements in the array that are greater than five
def sum_if_greater_than_five(arr: np.ndarray) -> int:
    return arr[arr > 5].sum().item()

**Correctness Verification:**

In [244]:
np_array = np.array([[3, 4, 5], 
                     [6, 7, 8]])
print("Sum of elements greater than five:")
print(sum_if_greater_than_five(np_array))

Sum of elements greater than five:
21


---

## 4. Loop Example in 2D Array

### Assignment 4.1: Sum each row manually using loops

**Explanation**: Use nested loops: `for row in arr: total += sum(row)`.

In [245]:
# TODO: Calculate the sum of each row in a 2D array using a for loop
def row_sums(arr: np.ndarray) -> np.ndarray:
    sums = np.zeros(arr.shape[0])
    for i in range(arr.shape[0]):
        sums[i] = arr[i].sum()
    return sums

**Correctness Verification:**

In [246]:
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("Sum of each row in the array:")
print(row_sums(np_array))

Sum of each row in the array:
[ 6. 15.]


### Assignment 4.2: Find max in each row of 2D array using loops

**Explanation**: Use a loop and `max()` on each row, then use `append()` to collect results to a list and convert it to a NumPy array.

In [247]:
# TODO: Find the maximum value in each row of a 2D array
def row_max(arr: np.ndarray) -> np.ndarray:
    max_values = np.zeros(arr.shape[0])
    for i in range(arr.shape[0]):
        max_values[i] = arr[i].max()
    return max_values

**Correctness Verification:**

In [248]:
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("Maximum value in each row of the array:")
print(row_max(np_array))

Maximum value in each row of the array:
[3. 6.]


### Assignment 4.3: Multiply each element by 2 using loops

**Explanation**: Traverse the array with loops and multiply each element.

In [249]:
# TODO: Multiply each element in the array by two
def multiply_by_two(arr: np.ndarray) -> np.ndarray:
    # method 1: Using a nested loop 
    # for i in range(arr.shape[0]):
    #     for j in range(arr.shape[1]):
    #         arr[i, j] *= 2

    #method 2: Flatten the array, multiply, and reshape
    flat = arr.flatten()
    flat *= 2
    arr = flat.reshape(arr.shape)

    return arr



**Correctness Verification:**

In [250]:
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array after multiplying each element by two:")
print(multiply_by_two(np_array))

Array after multiplying each element by two:
[[ 2  4  6]
 [ 8 10 12]]


---

## 5. Data Manipulation

### Shape and Reshaping

#### Assignment 5.1.1: Reshape a 3x4 array into 2x6

**Explanation**: Use `arr.reshape(new_shape)` where the new shape must have the same number of elements.

In [251]:
# TODO: Reshape a 3x4 array into a 2x6 array
def reshape_array(arr: np.ndarray) -> np.ndarray: # assuming the input is a 3x4 array
    return arr.reshape(2, 6)

**Correctness Verification:**

In [252]:
np_array_3_4 = np.array([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]])
print("Original array:")
print(np_array_3_4)
print("Reshaped array:")
print(reshape_array(np_array_3_4))

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


#### Assignment 5.1.2: Flatten the array into 1D

**Explanation**: Use `arr.flatten()` or `arr.reshape(-1)`.

In [253]:
# TODO: Flatten a 2D array into a 1D array
def flatten(arr: np.ndarray) -> np.ndarray:
    # return arr.flatten()
    return arr.reshape(-1)

**Correctness Verification:**

In [254]:
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(np_array)
print("Flattened array:")
print(flatten(np_array))

Original array:
[[1 2 3]
 [4 5 6]]
Flattened array:
[1 2 3 4 5 6]


### Array Iterating 2D Array

#### Assignment 5.2.1: Print all elements using np.nditer

**Explanation**: `np.nditer(arr)` allows iteration over all elements regardless of shape. Simply use `for element in np.nditer(arr):` to loop through each value. 

In [255]:
# TODO: Iterate through each element in the array and print it using np.nditer(arr)
def iterate_elements(arr: np.ndarray) -> None:
    for element in np.nditer(arr):
        print(element)

**Correctness Verification:**

In [256]:
np_array = np.array([[1, 2, 3], [4, 5, 6]])
iterate_elements(np_array)

1
2
3
4
5
6


#### Assignment 5.2.2: Return a list of elements > 5 using iteration

**Explanation**: Use `np.nditer(arr)` iteration to collect elements with condition: `if val > 5: result.append(val.item())`.

In [257]:
# TODO: Find elements greater than five in the array
def elements_greater_than_five(arr: np.ndarray) -> list:
    
    result = []
    for val in np.nditer(arr):
        if val > 5:
            result.append(val.item())
    return result

**Correctness Verification:**

In [258]:
np_array = np.array([[3, 4, 5], 
                     [6, 7, 8]])
print("Original array:")
print(np_array)
print("List of elements greater than five:")
print(elements_greater_than_five(np_array))

Original array:
[[3 4 5]
 [6 7 8]]
List of elements greater than five:
[6, 7, 8]


#### Assignment 5.2.3: Return sum using iteration

**Explanation**: Use `np.nditer(arr)` and add each element to a running total.

In [259]:
# TODO: Calculate the sum of all elements in the array using iteration with np.nditer(arr)
def sum_using_iteration(arr: np.ndarray) -> int:
    total = 0 
    for i in np.nditer(arr):
        total += i.item()
    return total

**Correctness Verification:**

In [260]:
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("Total sum of all elements in the array:")
print(sum_using_iteration(np_array))

Total sum of all elements in the array:
21


### Splitting 2D Arrays

#### Assignment 5.3.1: Split horizontally into two arrays

**Explanation**: Use `np.hsplit(arr, 2, axis=0)` for horizontal splits.

In [261]:
# TODO: Split a 2D array horizontally into two equal parts
def split_horizontal(arr: np.ndarray) -> list:
    return np.split(arr, 2, axis=0)

**Correctness Verification:**

In [262]:
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6],])
print("Original array:")
print(np_array)
print("Shape of the array:")
print(np_array.shape)
print("Split array horizontally:")
splits = split_horizontal(np_array)
for i, split in enumerate(splits):
    print(f"Split {i + 1}:")
    print(split)

Original array:
[[1 2 3]
 [4 5 6]]
Shape of the array:
(2, 3)
Split array horizontally:
Split 1:
[[1 2 3]]
Split 2:
[[4 5 6]]


#### Assignment 5.3.2: Split vertically into two arrays

**Explanation**: Use `np.vsplit(arr, 2, axis=1)` for vertical splits.

In [263]:
# TODO: Split a 2D array vertically into two equal parts
def split_vertical(arr: np.ndarray) -> list:
    return np.split(arr, 2, axis=1)

**Correctness Verification:**

In [264]:
np_array = np.array([[1, 2, 3, 4], 
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
print("Original array:")
print(np_array)
print("Shape of the array:")
print(np_array.shape)
splits = split_vertical(np_array)
for i, split in enumerate(splits):
    print(f"Split {i + 1}:")
    print(split)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of the array:
(3, 4)
Split 1:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
Split 2:
[[ 3  4]
 [ 7  8]
 [11 12]]


#### Assignment 5.3.3: Split into four quadrants

**Explanation**: First split by rows, then split each half by columns.

In [265]:
# TODO: Split a 2D array into four quadrants
def split_quadrants(arr: np.ndarray) -> list:
    top_half, bottom_half = np.split(arr, 2, axis=0)
    
    top_left, top_right = np.split(top_half, 2, axis=1)
    bottom_left, bottom_right = np.split(bottom_half, 2, axis=1)
    
    return [top_left, top_right, bottom_left, bottom_right]

**Correctness Verification:**

In [266]:
np_array = np.array([[1, 2, 3, 4], 
                     [5, 6, 7, 8],
                     [9, 10, 11, 12],
                     [13, 14, 15, 16]])
print("Original array:")
print(np_array)
print("Shape of the array:")
print(np_array.shape)
splits = split_quadrants(np_array)
for i, split in enumerate(splits):
    print(f"Quadrant {i + 1}:")
    print(split)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape of the array:
(4, 4)
Quadrant 1:
[[1 2]
 [5 6]]
Quadrant 2:
[[3 4]
 [7 8]]
Quadrant 3:
[[ 9 10]
 [13 14]]
Quadrant 4:
[[11 12]
 [15 16]]


### Array Slicing

#### Assignment 5.4.1: Get middle row of the array

**Explanation**: Use indexing like `arr[middle_index]` where index is `arr.shape[0]//2`.

In [267]:
# TODO: Return the middle row of a 2D array
def middle_row(arr: np.ndarray) -> np.ndarray:
    return arr[arr.shape[0] // 2]

**Correctness Verification:**

In [268]:
np_array = np.array([[1, 2],
                     [3, 4],
                     [5, 6]])
print("Original array:")
print(np_array)
print("Middle row of the array:")
print(middle_row(np_array))

Original array:
[[1 2]
 [3 4]
 [5 6]]
Middle row of the array:
[3 4]


#### Assignment 5.4.2: Get all corner elements (assuming square)

**Explanation**: Access `[0,0]`, `[0,-1]`, `[-1,0]`, and `[-1,-1]` from a 2D array.

In [269]:
# TODO: Return the corner elements of a 2D array
def corner_elements(arr: np.ndarray) -> list: # assuming arr is a 2D numpy square array
    return [
        arr[0, 0].item(),      
        arr[0, -1].item(),     
        arr[-1, 0].item(),   
        arr[-1, -1].item()   
    ]

**Correctness Verification:**

In [270]:
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(np_array)
print("Corner elements of the array:")
print(corner_elements(np_array))

Original array:
[[1 2 3]
 [4 5 6]]
Corner elements of the array:
[1, 3, 4, 6]


#### Assignment 5.4.3: Return sub-array from index [start_row:end_row, start_col:end_col]

**Explanation**: Use slicing like `arr[1:3, 1:3]` to extract a sub-array.

In [271]:
# TODO: Return a sub-array from the original array
def sub_array(arr: np.ndarray, start_row: int, end_row: int, start_col: int, end_col: int) -> np.ndarray:
    return arr[start_row:end_row, start_col:end_col]

**Correctness Verification:**

In [272]:
np_array = np.array([[1, 2, 3, 4], 
                     [5, 6, 7, 8],
                     [9, 10, 11, 12],
                     [13, 14, 15, 16]])
print("Original array:")
print(np_array)
print("Sub-array from index [1:3, 1:3]:")
print(sub_array(np_array, 1, 3, 1, 3))

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sub-array from index [1:3, 1:3]:
[[ 6  7]
 [10 11]]
